config/routes.rb
OpinionsProject::Application.routes.draw do

  get "votes/create"
  devise_for :users
  root 'static_pages#index'
  get '/home' => 'white_pages#home', as: :home
  get '/about' => 'white_pages#about', as: :about

  resources :opinions do   
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :articles do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :votes, :as => :voteable
	has_many :comments, :as => :commentable

	validates :title, :body, presence: true 
	validates :body, length: { in: 10..1000 }
	validates :title, length: { in: 5..50 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :votes
	belongs_to :commentable, :polymorphic => true
	belongs_to :user
	validates :body, presence: true

	def parent
		commentable_type.constantize.find(commentable_id)
	end

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
	belongs_to :user
	has_many :votes, :as => :voteable
	has_many :comments, :as => :commentable

	validates :title, :body, presence: true 
	validates :body, length: { in: 10..255 }
	validates :title, length: { in: 5..50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :votes
  has_many :comments
  has_many :opinions
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :opinion
	belongs_to :voteable, :polymorphic => true
	belongs_to :article
	belongs_to :comment

	def parent
		voteable_type.constantize.find(voteable_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :null_session

  def current_user_has_voted?(object)
    object.votes.exists?(user_id: current_user.id)
  end

  def vote_average(object)
    sum = 0
    object.votes.each do |vote|
      sum += vote.quality
    end

    if object.votes.count > 0
      @vote_average = sum / object.votes.count 
    else 
      @vote_average = 0
    end
  end

  def load_parent
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

  protected

  def configure_devise_permitted_parameters
    registration_params = [:user_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]


	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to article_path(@article.id)
		else
			render :new
		end
	end

	def show
		@article = Article.find(params[:id])
		@comments = @article.comments
		@comment = Comment.new
	end

	def update
		Article.update(article_params)
		redirect_to article_path(@article.id)
	end

	def vote
		if params[:polarity] == true || params[:polarity] = false
			Vote.create(user_id: current_user.id, polarity: params[:polarity], article_id: params[:id])
		end
		redirect_to article_path(params[:id])
	end



	private

	def article_params
		params.require(:article).permit(:title,:body,:user_id)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@commentable = load_parent
		@comment = @commentable.comments.build(comment_params)
		@comment.user_id = current_user.id
		@comment.save
		redirect_to @comment.parent
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :commentable_type, :commentable_id)
	end

end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]
	skip_before_action :verify_authenticity_token, :only => [:vote]


	def index
		@opinions = Opinion.all.sort_by
	end

	def new
		@opinion = Opinion.new
	end

	def create
		@opinion = Opinion.create(opinion_params)
		if @opinion.save
			redirect_to opinion_path(@opinion.id)
		else
			render :new
		end
	end

	def show
		@opinion = Opinion.find(params[:id])
		@comments = @opinion.comments
		@comment = Comment.new
		@vote = Vote.new
		@vote_average = vote_average(@opinion).round
		@voted = current_user_has_voted?(@opinion) 
	end

	def vote
		@vote = Vote.create(user_id: current_user.id, quality: params[:quality], opinion_id: params[:id])
		redirect_to opinion_path(params[:id])
	end

	private

	def opinion_params
		params.require(:opinion).permit(:title,:body,:user_id)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	layout 'static'

	def index
		if current_user
			redirect_to home_path
		end
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
  	@voteable = load_parent
  	@vote = @voteable.votes.build(vote_params)
  	@vote.user_id = current_user.id
  	@vote.save
  	redirect_to @vote.parent
  end

  private

  def vote_params
  	params.require(:vote).permit(:quality)
  end
end

app/controllers/white_pages_controller.rb
class WhitePagesController < ApplicationController

	def home
		@data = Opinions::SportsData.get_data
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/white_pages_helper.rb
module WhitePagesHelper
end

app/views/articles/index.html.erb
<%= render 'layouts/header'  %>

<h2>Articles</h2>


<% @articles.each do |article| %>
	 <%= link_to "#{article.title}", article_path(article.id) %>
<% end %>

app/views/articles/new.html.erb
<% unless @article.errors.empty? %>
	<% @article.errors.each do |error| %>
	<%= error.message %>
	<% end %>
<% end %>

<div class='new-article-container'>
<%= form_for @article, {:class => 'new-article-form'} do |f| %>
	
	<%= f.text_field :title, placeholder: "Title here", class: 'new-article-text text-field' %>

	<%= f.text_area :body, placeholder: "Write post here", class: 'new-article-text text-area' %>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<%= f.submit 'Post', class: 'btn new-article-button btn-lg' %>

<% end %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h4><%= @article.user.user_name %></h4>
<p><%= @article.body %></p>

<% if user_signed_in? %>
	<%= form_for @comment do |f| %>

		<%= f.text_field :body %>

		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.hidden_field :article_id, :value => @article.id %>

		<%= f.submit "Post" %>
	<% end %>
<% else %>
	<p>You must <%= link_to 'sign in', new_user_registration_path %> to comment </p>
<% end %>

<% unless @comments.empty? %>
	<% @comments.each do |comment| %>
		<%= comment.user.user_name %>
		<%= comment.body %>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pull-left">
	<div class='container'>
	<p class='text-center'>
		<% unless current_user %>
			w<%= link_to 'sign in', new_user_session_path%>
		<% end %>
		<%= link_to 'about us', about_path%>
		<%= link_to 'home', home_path%>
		<%= link_to 'articles', articles_path%>
		<%= link_to 'opinions', opinions_path%></p>
	</div>
</footer>

app/views/layouts/_footer_white.html.erb
<footer class="pull-left">
	<div class='container'>
	<p class='text-center'>
		<% unless user_signed_in? %>
			<%= link_to 'sign in', new_user_session_path, class: 'footer-white-bg'%>
		<% end %>
		<%= link_to 'about us', about_path, class: 'footer-white-bg'%>
		<%= link_to 'home', home_path, class: 'footer-white-bg'%>
		<%= link_to 'articles', articles_path, class: 'footer-white-bg'%>
		<%= link_to 'opinions', opinions_path, class: 'footer-white-bg'%></p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-defaults" role="navigation">
  <div class="container-nav">
   	<h1 class="pull-left"><%= link_to "Name", root_path %></h1>
   	
  </div>
</nav>

app/views/layouts/_off_canvas_menu.html.erb
<button class="uk-button-large" data-uk-offcanvas="{target:'#my-id'}"><span class="glyphicon glyphicon-th-list"></span> Menu</button>

		<!-- This is the off-canvas sidebar -->
		<div id="my-id" class="uk-offcanvas">
		    <div class="uk-offcanvas-bar">
		        <ul class="uk-nav uk-nav-offcanvas uk-text-right" data-uk-nav>
		        	<li><%= link_to "home", root_path  %></li>		        	
		        	<li><%= link_to "articles", articles_path %></li>
		        	<li><%= link_to "opinions", opinions_path %></li>

		        	<% unless user_signed_in? %>
							<li><%= link_to 'sign in', new_user_session_path %></li>
							<% else %>
							<li><%= link_to 'edit profile', edit_user_registration_path %></li>
							<li><%= link_to 'sign out', destroy_user_session_path, method: :delete%></li>
							<% end %>
		        </ul>
		    </div>
		</div>

app/views/layouts/_submit_form.html.erb
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :body %>
	<%= f.text_area :body %>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<%= f.submit 'Post' %>

app/views/layouts/_vote.html.erb
<% if user_signed_in? %>
	<% if @opinion.votes.exists?(user_id: current_user.id) %>
		<button class='btn btn-large' disabled>
			<%= link_to("Upvote", vote_opinion_path(@opinion, 'true'), method: 'post')%>  
		</button>
		<button class='btn btn-large' disabled>
		<%= link_to("Downvote", vote_opinion_path(@opinion, 'false'), method: 'post')  %>
		</button>
	<% else %>
		<button class='btn btn-large'>
			<%= link_to("Upvote", vote_opinion_path(@opinion, 'true'), method: 'post')%>  
		</button>
		<button class='btn btn-large'>
		<%= link_to("Downvote", vote_opinion_path(@opinion, 'false'), method: 'post')  %>
		</button>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpinionsProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", '//fonts.googleapis.com/css?family=Raleway', :media => "all" %>
</head>
<body>
		<!-- 	<p class="notice"><%#= notice %></p>
		 	<p class="alert"><%#= alert %></p> -->
		 	<!-- This is the button toggling the off-canvas sidebar -->
			<%= render "layouts/off_canvas_menu"  %>
			

			<%= yield %>


</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpinionsProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='static'>

<%= yield %>

</body>
</html>

app/views/opinions/index.html.erb
<%= render 'layouts/header'  %>

<div class="cover-image">
	<div class="cover-image blurred-img"></div>
</div>
<div class='cover-title center'>
	<h1 style="font-weight: 100;">Opinions</h1>
	<p>The place for those short, quick hitting opinions that are itching to get out.</p>
	<br>
		<%= link_to 'Post an opinion', new_opinion_path, class: 'new-opinion btn btn-primary btn-large' %>
</div>

<div class='opinions-list'>
	<p class='trending-title'>
		<span class='glyphicon glyphicon-chevron-down'></span>  trending opinions 
	</p>
<% @opinions.each do |opinion| %>
<div class='opinions'>
	<!-- <p class='vote-count'><%#= opinion.upvote_count %>...<%#= opinion.downvote_count %></p> -->
	<p><%= link_to "#{opinion.title}", opinion_path(opinion), class: 'opinions-titles center' %>
		<br><span class='opinion-user'>by <%= opinion.user.user_name %></span></p>
	<p><%= link_to "Comments: #{opinion.comments.size}", opinion_path(opinion), class: 'opinions-comments' %></p>
</div>
<% end %>
</div>

app/views/opinions/new.html.erb
<% if @opinion.errors.any? %>
	<div id='error_explanation'>
		<h3><%= pluralize(@opinion.errors.count, 'error') %> prohibited the post</h3>

		<ul>
			<% @opinion.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
<% end %>


<a href="<%= opinions_path %>"><span class='
glyphicon glyphicon-chevron-left'></span></a>

<div class='new-opinion-container'>
<%= form_for @opinion, {:class => 'new-opinion-form'} do |f| %>
	
	<%= f.text_field :title, placeholder: "Title here", class: 'new-opinion-text text-field' %>

	<%= f.text_area :body, placeholder: "What is your sports opinion?", class: 'new-opinion-text text-area' %>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<%= f.submit 'Post', class: 'btn new-opinion-button btn-lg' %>

<% end %>
</div>

app/views/opinions/show.html.erb
<div class='container'>
<div class="progress progress-striped">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @vote_average %>%;"> 
  	<%= @vote_average %>%
  </div>
</div>

<p>What do you think?</p>
	<%= form_for [@opinion, @vote] do |f| %>
		<p><%= f.range_field :quality, :min=>0, :max=>100, :class=>"slide"%></p>
		<% if @voted %>
			<%= f.submit "Vote", disabled: true %>
		<% else %>
			<%= f.submit "Vote" %>
		<% end %>
	<% end %>
		
<div class='panel panel-default'>
	<div class='panel-heading'>
		<h1 class='opinion-title'><%= @opinion.title %></h1>
	</div>
	<div class='panel-body'> 
		<p class='opinion-body'><%= @opinion.body %></p>
	</div>
	<div class='panel-footer'>
		<% if user_signed_in? %>
			<%= form_for [@opinion, @comment] do |f| %>
				<%= f.text_field :body, class: 'form-control submit-comment', placeholder: 'Have a comment?'%>
				<%= f.submit 'Post', class: 'btn btn-primary opinion-btn post' %>
			<% end %>
		<% else %>
			<p class='center'>You must <%= link_to 'sign in', new_user_session_path %> to comment </p>
		<% end %>
		<% unless @comments.empty? %>
			<% @comments.each do |comment| %>
				<p class='well'>
					<%= comment.user.user_name %>: 
					<%= comment.body %>
				</p>
			<% end %>
		<% end %>
	</div>
</div>

app/views/static_pages/index.html.erb
<div class='home-container'>
	<h1 class='home-title'>Sports Opinions</h1>
	<h2 class='home-title'>Every sports fan has an opinion. Share yours today.</h2>

	<%= link_to 'Sign up', new_user_registration_path, class: 'signup btn btn-primary btn-large' %>

			
</div>
<%= render 'layouts/footer' %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/white_pages/home.html.erb
<%= @data.inspect %>